pipeline {
    agent any  
    environment {
        AWS_DEFAULT_REGION = 'eu-central-1'
        ECR_REPOSITORY = '049013287065.dkr.ecr.eu-central-1.amazonaws.com/springboot'
    }
    stages {
        stage ('Build') {
            steps {
                sh 'nice ./mvnw -f spring-boot-samples/spring-boot-sample-web-ui/pom.xml clean package -DskipTests'
            }
        }
        stage ('Docker push') {
            steps {
                sh 'aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REPOSITORY}'
                sh 'docker build -f spring-boot-samples/spring-boot-sample-web-ui/Dockerfile -t ${ECR_REPOSITORY}:${BUILD_NUMBER} .'                   
                sh 'docker push ${ECR_REPOSITORY}:${BUILD_NUMBER}'
                echo "${BUILD_NUMBER}"
                // get commit info
                echo "${GIT_PREVIOUS_SUCCESSFUL_COMMIT}"
                echo "${GIT_PREVIOUS_COMMIT}"
            }        
        }
        stage ('Deploy from AWS ECR to web-srv') {
            steps {
                // sh "ssh ubuntu@172.31.41.201 'aws ecr get-login-password --region ${AWS_DEFAULT_REGION}'"
                sh "ssh ubuntu@172.31.41.201 'docker run --rm -d -p 8080:8080 ${ECR_REPOSITORY}:${BUILD_NUMBER}'"                
            } 
        }
    }    
}
